selection:
  save_to_clipboard: true
    
window:
  opacity: 0.8
  decorations: full
  padding:
    x: 10
    y: 10
  startup_mode: Maximized

font:
  size: 11.5
  normal:
    family: monospace
    style: Regular

colors:
  primary:
    background: '#000000'
    cursor: '#FECA88'

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

key_bindings:
  - { key: PageUp, action: ScrollHalfPageUp }
  - { key: PageDown, action: ScrollHalfPageDown }
