autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    username: probua
    password: "$6$ZE4WV3QRJhPUnsNv$BpkTBYjUOxOiWV5sNPYDSitTwxW.3NHLmhRqptzpa8a4KTxGpkvMaSDbyq4PVri9kdpD1t7ldUBgwB6uveObg."

  snaps:
    - name: aws-cli
      classic: true
    - name: code
      classic: true
    - name: obsidian
      classic: true
    - name: dbeaver-ce
      classic: false
    - name: postman
      classic: false
    - name: teams-for-linux
      classic: false

  packages:
    - curl
    - vim
    - rofi
    - dmenu
    - git
    - feh
    - picom
    - arandr
    - i3
    - i3status
    - i3blocks
    - brightnessctl
    - playerctl
    - keepassxc
    - alacritty
    - thunar
    - fonts-font-awesome
    - blueman
    - pulseaudio-utils

  late-commands:
    - curtin in-target curl -o- -L https://slss.io/install | bash
    - curtin in-target curl -o- -L https://raw.githubusercontent.com/probua/home/main/config/ubuntu/install-kmonad.sh | bash
    - curtin in-target curl -o- -L https://raw.githubusercontent.com/probua/home/main/config/ubuntu/install-docker.sh | bash
    - curtin in-target usermod -aG docker probua
    - curtin in-target usermod -aG video probua
    - curtin in-target curl -o- -L https://raw.githubusercontent.com/probua/home/main/config/ubuntu/install-config.sh | bash