selection:
  save_to_clipboard: true
    
window:
  opacity: 0.9
  decorations: full
  padding:
    x: 5
    y: 5
  startup_mode: Windowed

font:
  size: 10
  normal:
    family: Hack
    style: Regular

colors:
  primary:
    background: '#1e2229'
    foreground: '#c5c8c6'
