# Windows
#shell:
#  program: "C:\\Program Files\\Git\\bin\\bash.exe"
#key_bindings:
#  - { key: T, mods: Control|Alt, action: SpawnNewInstance }

selection:
  save_to_clipboard: true
    
window:
  opacity: 0.9
  decorations: full
  padding:
    x: 15
    y: 15
  startup_mode: Windowed
