set number
#set relativenumber
set mouse=a
set numberwidth=1
set clipboard=unnamed
set showcmd
set ruler
set encoding=utf-8
set showmatch
set laststatus=2
set splitbelow
set splitright
"set cursorline

" Terminal size
set termwinsize=10*0
"Tabs
set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4
"set noshowmode
syntax enable

" Install vim-plug: https://github.com/junegunn/vim-plug
call plug#begin('~/.vim/plugged')

" Languages
Plug 'sheerun/vim-polyglot'

" IDE
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdtree'
Plug 'christoomey/vim-tmux-navigator'

call plug#end()

"colorscheme gruvbox
"let g:gruvbox_contrast_dark = "hard"
let NERDTreeQuitOnOpen=1
let mapleader=" "

" Hotkeys
nmap <Leader>s <Plug>(easymotion-s2)
nmap <Leader>nt :NERDTreeFind<CR>
nmap <c-b> :NERDTreeToggle<CR>
nmap <c-t> :below terminal<CR>

" Tabs
nmap <tab> >>
nmap <s-tab> <<
vmap <tab> >gv
vmap <s-tab> <gv

" Split resize
nmap <s-left> 1<c-w><
nmap <s-right> 1<c-w>>
nmap <s-up> 1<c-w>+
nmap <s-down> 1<c-w>-

" Faster scrolling / side moving
nmap <c-up> 10k
nmap <c-down> 10j
nmap <c-left> gE
nmap <c-right> W

cnoreabbrev nt NERDTreeToggle
command! NT :NERDTreeToggle
command! W :w
command! Wq :wq
command! WQ :wq
command! Q :q

" Alt-arrows
nmap <a-left> <c-h>
nmap <a-right> <c-l>
nmap <a-up> <c-k>
nmap <a-down> <c-j>

nmap <Leader>vs :vsplit<CR>
nmap <Leader>sp :split<CR>

